# fly.toml app configuration file generated for peercode-signaling-server on 2023-08-25T00:21:27+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "peercode-signaling-server"
primary_region = "ams"
max-per-region=1
kill_signal = "SIGINT"
kill_timeout = 5
[build]

[http_service]
  internal_port = 4444
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  cpus = 1
  memorymb = 256
  cpu_kind = "shared"
  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25
#[[services.http_checks]]
#    interval = 10000
#    grace_period = "5s"
#    method = "get"
#    path = "/actuator/health"
#    protocol = "http"
#    restart_limit = 0
#    timeout = 2000
#    tls_skip_verify = false
#[deploy]
#  strategy = "bluegreen"