name: Deploy to Flyio

on:
  push:
    branches: [ main ]
#  workflow_run:
#    workflows:
#      - "Build"
#    branches:
#      - main
#    types:
#      - completed
#  workflow_dispatch:


jobs:
  deploy:
    #    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
